  # jest:
  #   name: js-tests
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: Checkout code
  #     uses: actions/checkout@v2

  #   - name: Get Yarn cache directory
  #     id: yarn-cache-dir
  #     run: echo "::set-output name=dir::$(yarn cache dir)"

  #   - name: Cache node modules
  #     id: yarn-cache
  #     uses: actions/cache@v2.1.4
  #     with:
  #       path: ${{ steps.yarn-cache-dir.outputs.dir }}
  #       key: ${{ runner.os }}-js-${{ hashFiles('**/yarn.lock') }}
  #       restore-keys: |
  #         ${{ runner.os }}-js-

  #   - name: yarn install
  #     run:  yarn install --dev

  #   - name: Run tests
  #     run: yarn test --passWithNoTests
  # rubocop:
  #   name: rubocop
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Install libraries
  #       run: |
  #         sudo apt-get update
  #         sudo apt-get install -y libpq-dev
  #     - name: Set up Ruby
  #       uses: ruby/setup-ruby@v1
  #       with:
  #         bundler-cache: true

  #     - uses: actions/checkout@v2.3.4

  #     - name: Run rubocop checks
  #       run: bundle exec rubocop -D

