name: CI
on: [push, pull_request]
jobs:
  specs:
    name: specs
    runs-on: ubuntu-latest
    services: 
      postgres:
        image: postgres:10.12
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          REDIS_URL: redis://localhost:6379/0
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
      redis:
        image: redis
        ports:
          - 6379:6379
        options: --health-cmd "redis-cli ping" --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
    - name: Install Libraries
      run: |
        sudo apt-get update
        sudo apt-get install -y postgresql-client libpq-dev
    - name: Checkout code
      uses: actions/checkout@v2.3.4

    - name: Setup Ruby
      uses: actions/setup-ruby@v1.1.3
      with:
        ruby-version: 2.7

    - name: Cache gems
      uses: actions/cache@v2.1.4
      with:
        path: vendor/bundle
        key: bundle-use-ruby-${{ runner.os }}-${{ hashFiles('.ruby-version') }}-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          bundle-use-ruby-${{ runner.os }}-${{ hashFiles('.ruby-version') }}-

    - name: Install Bundler and gems
      run: |
        gem install bundler --no-document
        bundle config GITHUB__COM $GITHUB_ACCESS_TOKEN
        bundle install --jobs 4 --retry 3
      env:
        RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
        REDIS_URL: redis://localhost:6379/0

    - name: Get Yarn cache directory
      id: yarn-cache-dir
      run: echo "::set-output name=dir::$(yarn cache dir)"

    - name: Cache node modules
      id: yarn-cache
      uses: actions/cache@v2.1.4
      with:
        path: ${{ steps.yarn-cache-dir.outputs.dir }}
        key: ${{ runner.os }}-js-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-js-

    - name: yarn install
      run:  yarn install --dev

    - name: Run tests
      env:
        RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        REDIS_URL: redis://localhost:6379/0
      run: |
        cp config/database.yml.github-actions config/database.yml
        pg_config --version
        bin/rails db:create RAILS_ENV=test
        bin/rails db:migrate RAILS_ENV=test
        bundle exec rspec
  # jest:
  #   name: js-tests
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: Checkout code
  #     uses: actions/checkout@v2

  #   - name: Get Yarn cache directory
  #     id: yarn-cache-dir
  #     run: echo "::set-output name=dir::$(yarn cache dir)"

  #   - name: Cache node modules
  #     id: yarn-cache
  #     uses: actions/cache@v2.1.4
  #     with:
  #       path: ${{ steps.yarn-cache-dir.outputs.dir }}
  #       key: ${{ runner.os }}-js-${{ hashFiles('**/yarn.lock') }}
  #       restore-keys: |
  #         ${{ runner.os }}-js-

  #   - name: yarn install
  #     run:  yarn install --dev

  #   - name: Run tests
  #     run: yarn test --passWithNoTests
  rubocop:
    name: rubocop
    runs-on: ubuntu-latest
    steps:
      - name: Install libraries
        run: |
          sudo apt-get update
          sudo apt-get install -y libpq-dev
      - name: Set up Ruby
        uses: actions/setup-ruby@v1.1.3
        with:
          ruby-version: 2.7

      - uses: actions/checkout@v2.3.4

      - name: Cache gems
        uses: actions/cache@v2.1.4
        with:
          path: vendor/bundle
          key: bundle-use-ruby-${{ runner.os }}-${{ hashFiles('.ruby-version') }}-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            bundle-use-ruby-${{ runner.os }}-${{ hashFiles('.ruby-version') }}-

      - name: Install bundler and rubocop
        run: |
          gem install bundler --no-document
          bundle config GITHUB__COM $GITHUB_ACCESS_TOKEN
          bundle install --jobs 4 --retry 3 --with=test
        env:
          GITHUB_ACCESS_TOKEN: $

      - name: Run rubocop checks
        run: bundle exec rubocop -D
